import type { HazardZone, RideOption, RouteOption, TelemetryMetric, TravelMode, Waypoint } from './types'

export const travelModes: TravelMode[] = [
  {
    id: 'wormhole',
    label: '虫洞优先',
    description: '最少跳迁',
    icon: 'vortex',
  },
  {
    id: 'low-radiation',
    label: '低辐射',
    description: '避开风暴',
    icon: 'shield',
  },
  {
    id: 'economy',
    label: '补给站',
    description: '低燃耗',
    icon: 'supply',
  },
]

export const waypoints: Waypoint[] = [
  {
    id: 'earth-port',
    label: '地球轨道港',
    shortLabel: '地球',
    role: 'origin',
    x: 146,
    y: 405,
    time: '出发',
    note: '主推进校准完成',
  },
  {
    id: 'sirius-jump',
    label: '天狼跃迁点',
    shortLabel: '天狼',
    role: 'transfer',
    x: 205,
    y: 332,
    time: '0.6 光时',
  },
  {
    id: 'xuanyuan-station',
    label: '轩辕枢纽站',
    shortLabel: '轩辕',
    role: 'supply',
    x: 326,
    y: 320,
    time: '1.1 光时',
    note: '补给站',
  },
  {
    id: 'centauri-jump',
    label: '半人马跃迁点',
    shortLabel: '半人马',
    role: 'transfer',
    x: 430,
    y: 250,
    time: '0.9 光时',
  },
  {
    id: 'orion-jump',
    label: '参宿四跃迁点',
    shortLabel: '参宿四',
    role: 'transfer',
    x: 514,
    y: 168,
    time: '0.7 光时',
  },
  {
    id: 'aldebaran-jump',
    label: '毕宿五跃迁点',
    shortLabel: '毕宿五',
    role: 'transfer',
    x: 617,
    y: 182,
    time: '0.4 光时',
  },
  {
    id: 'mars-relay',
    label: '火星中继站',
    shortLabel: '火星',
    role: 'destination',
    x: 780,
    y: 274,
    time: '到达',
  },
]

export const routeOptions: RouteOption[] = [
  {
    id: 'wormhole',
    label: '推荐',
    mode: '虫洞优先',
    duration: '3.7 光时',
    stops: 12,
    risk: 'low',
    color: '#27f5f2',
    path: [
      'earth-port',
      'sirius-jump',
      'xuanyuan-station',
      'centauri-jump',
      'orion-jump',
      'aldebaran-jump',
      'mars-relay',
    ],
    alerts: ['低辐射', '补给站', '跃迁稳定'],
  },
  {
    id: 'low-radiation',
    label: '备选',
    mode: '低辐射',
    duration: '4.6 光时',
    stops: 16,
    risk: 'medium',
    color: '#ffad2f',
    path: [
      'earth-port',
      'sirius-jump',
      'xuanyuan-station',
      'centauri-jump',
      'mars-relay',
    ],
    alerts: ['绕行辐射带', '燃耗增加'],
  },
  {
    id: 'economy',
    label: '备选',
    mode: '经济模式',
    duration: '5.2 光时',
    stops: 18,
    risk: 'medium',
    color: '#7fd4ff',
    path: [
      'earth-port',
      'xuanyuan-station',
      'orion-jump',
      'aldebaran-jump',
      'mars-relay',
    ],
    alerts: ['补给密集', '低燃耗'],
  },
]

export const rideOptions: RideOption[] = [
  {
    id: 'orbital-shuttle',
    label: '轨道快船',
    badge: '推荐',
    description: '直达航线 · 快速稳定',
    eta: '3 分钟接驾',
    duration: '2 小时 28 分送达',
    price: '320 星币',
    vehicle: 'orbital',
  },
  {
    id: 'warp-premium',
    label: '跃迁专车',
    description: '高速抵达 · 独立舱位',
    eta: '5 分钟接驾',
    duration: '1 小时 12 分送达',
    price: '520 星币',
    vehicle: 'warp',
  },
  {
    id: 'shared-cabin',
    label: '拼舱',
    description: '拼舱出行 · 经济实惠',
    eta: '8 分钟接驾',
    duration: '4 小时 45 分送达',
    price: '160 星币',
    vehicle: 'shared',
  },
]

export const hazardZones: HazardZone[] = [
  {
    id: 'radiation-belt',
    label: '辐射带',
    level: '中等',
    tone: 'amber',
    x: 664,
    y: 412,
    radius: 58,
  },
  {
    id: 'micro-asteroids',
    label: '小行星带',
    level: '中等',
    tone: 'amber',
    x: 432,
    y: 470,
    radius: 42,
  },
  {
    id: 'magnetic-storm',
    label: '电磁风暴区',
    level: '高',
    tone: 'magenta',
    x: 748,
    y: 438,
    radius: 70,
  },
  {
    id: 'gravity-vortex',
    label: '引力漩涡',
    level: '低',
    tone: 'cyan',
    x: 806,
    y: 342,
    radius: 36,
  },
]

export const telemetryMetrics: TelemetryMetric[] = [
  {
    id: 'fuel',
    label: '剩余燃料',
    value: '78%',
    level: 78,
    icon: 'fuel',
  },
  {
    id: 'jump',
    label: '跃迁能量',
    value: '92%',
    level: 92,
    icon: 'bolt',
  },
  {
    id: 'shield',
    label: '护盾强度',
    value: '100%',
    level: 100,
    icon: 'shield',
  },
  {
    id: 'integrity',
    label: '船体完整性',
    value: '100%',
    level: 100,
    icon: 'ship',
  },
  {
    id: 'speed',
    label: '航行速度',
    value: '0.78 c',
    level: 48,
    icon: 'speed',
  },
]

export const starField = [
  [72, 91, 1],
  [119, 183, 2],
  [181, 118, 1],
  [245, 226, 2],
  [294, 92, 1],
  [352, 156, 3],
  [404, 89, 1],
  [463, 350, 2],
  [516, 74, 1],
  [574, 276, 2],
  [638, 95, 1],
  [703, 221, 3],
  [760, 118, 1],
  [832, 311, 2],
  [891, 184, 1],
  [946, 84, 2],
  [93, 508, 1],
  [183, 547, 2],
  [286, 448, 1],
  [366, 512, 2],
  [538, 484, 1],
  [615, 565, 2],
  [811, 538, 1],
  [926, 472, 2],
] as const
